name: Push

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: rubilmax/evm-maths/.github/workflows/test.yml@main

  release:
    needs: test

    uses: rubilmax/evm-maths/.github/workflows/release.yml@main
    secrets: inherit
