name: Push

on:
  push:
    branches:
      - main
      - ethers-v5
      - ethers-v6

jobs:
  test:
    uses: rubilmax/ethers-maths/.github/workflows/test.yml@main

  release:
    needs: test

    uses: rubilmax/ethers-maths/.github/workflows/release.yml@main
    secrets: inherit
